### PR TITLE
Added right click context menu, refactored and modularized, updated settings form

### PR DESCRIPTION
**Pull request by cboseak**
updated a few things to close out the issue previously reported.

### CODE REVIEW

**Comment by bitdust** [comment]
Thanks for the PR. 
And it's really a nice job to write logic in single function.

**Comment by cboseak** [comment]
Thanks for the merge! This is a great program, nice work. Also, I might move all the logic to its own class(saw your comment in the original code)

**Comment by bitdust** [comment]
Merry Christmas! (I know this could be a little too early for you,but whatever)

EarthLive# 2.0 was released thanks to your contribution.

**Comment by cboseak** [comment]
I just downloaded 2.0. It looks great! 

also, I saw the issue about bandwidth. I have a VPS you can use if you like, unlimited bandwidth.

**Comment by bitdust** [comment]
That is so nice of you.
But i think we shouldnt build the buffer on our own host. As you know, whart we are building is an Software. It should not be our responsiblity to offer a Free image feeds service(espicially when we dont hold the copyright of those images). Also i have clarified this to those users in Chinese.
Finally, so sorry for my poor English and I wish i'm not writing something wrong/impolite...

**Comment by cboseak** [comment]
no worries. I think a possible future feature would be the ability to pull images to an ftp and then pull from ftp. Or possibly rotate to different satellite images so the load is spread to multiple sources. May tinker around and let you know what I find.

**Pull request merged**
